localStorage['pond2'] = JSON.stringify(
{ "height":5,
 "layers":[
        {
         "data":[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 17, 2, 2, 2, 2, 2, 2, 3, 3, 1, 3, 2, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 12, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3],
         "height":5,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }],
 "orientation":"isometric",
 "properties":
    {

    },
 "tileheight":40,
 "tilesets":[
        {
         "firstgid":1,
         "image":"grass-tile.png",
         "imageheight":160,
         "imagewidth":240,
         "margin":0,
         "name":"grass tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"1,0",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"1,1",
                 "tileID":"4"
                },
             "5":
                {
                 "coords":"1,2",
                 "tileID":"5"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":7,
         "image":"water-tile1.png",
         "imageheight":160,
         "imagewidth":240,
         "margin":0,
         "name":"water tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"1,0",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"1,1",
                 "tileID":"4"
                },
             "5":
                {
                 "coords":"1,2",
                 "tileID":"5"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":13,
         "image":"stone-tile.png",
         "imageheight":160,
         "imagewidth":240,
         "margin":0,
         "name":"stone tiles",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"1,0",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"1,1",
                 "tileID":"4"
                },
             "5":
                {
                 "coords":"1,2",
                 "tileID":"5"
                }
            },
         "tilewidth":80
        }],
 "tilewidth":80,
 "version":1,
 "width":10
}
);