localStorage['pond'] = JSON.stringify(

{ "height":15,
 "layers":[
        {
         "data":[16, 17, 2, 2, 2, 2, 2, 2, 2, 1, 1, 5, 5, 4, 4, 1, 17, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 5, 5, 4, 1, 2, 2, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 5, 5, 2, 2, 2, 3, 12, 12, 3, 3, 3, 3, 2, 2, 1, 1, 1, 2, 2, 3, 3, 12, 9, 12, 12, 12, 3, 3, 2, 2, 1, 1, 2, 2, 3, 12, 9, 9, 9, 9, 9, 12, 3, 3, 2, 2, 2, 2, 3, 3, 12, 9, 9, 9, 9, 9, 9, 12, 3, 3, 2, 2, 2, 3, 12, 9, 9, 9, 9, 9, 9, 9, 9, 12, 3, 2, 2, 2, 3, 3, 12, 9, 9, 9, 9, 9, 9, 9, 12, 3, 2, 2, 2, 2, 3, 3, 12, 12, 12, 12, 12, 12, 12, 3, 3, 2, 1, 2, 2, 2, 3, 3, 12, 3, 3, 3, 3, 3, 3, 2, 2, 1, 1, 1, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 14, 14, 2, 2, 2, 2, 2, 14, 13, 5, 5, 5, 5, 5, 1, 1, 14, 2, 2, 2, 2, 2, 13, 16, 17, 4, 4, 4, 5, 5, 1, 2, 2, 2, 2, 1, 1, 1, 17, 5, 4, 4],
         "height":15,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }],
 "orientation":"isometric",
 "properties":
    {

    },
 "tileheight":40,
 "tilesets":[
        {
         "firstgid":1,
         "image":"grass-tile.png",
         "imageheight":160,
         "imagewidth":240,
         "margin":0,
         "name":"grass tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"1,0",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"1,1",
                 "tileID":"4"
                },
             "5":
                {
                 "coords":"1,2",
                 "tileID":"5"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":7,
         "image":"water-tile1.png",
         "imageheight":160,
         "imagewidth":240,
         "margin":0,
         "name":"water tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"1,0",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"1,1",
                 "tileID":"4"
                },
             "5":
                {
                 "coords":"1,2",
                 "tileID":"5"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":13,
         "image":"stone-tile.png",
         "imageheight":160,
         "imagewidth":240,
         "margin":0,
         "name":"stone tiles",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"1,0",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"1,1",
                 "tileID":"4"
                },
             "5":
                {
                 "coords":"1,2",
                 "tileID":"5"
                }
            },
         "tilewidth":80
        }],
 "tilewidth":80,
 "version":1,
 "width":15
}

);