localStorage['start'] = JSON.stringify(
{ "height":15,
 "layers":[
        {
         "data":[1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 6, 6, 7, 8, 9, 7, 6, 6, 7, 9, 9, 8, 8, 7, 7, 16, 16, 17, 18, 19, 18, 18, 18, 18, 19, 19, 18, 18, 17, 17, 6, 6, 7, 8, 9, 7, 6, 6, 7, 9, 9, 8, 8, 7, 7, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 1, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 2, 2, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 2, 3, 3, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 2, 3, 4, 4, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2, 1, 2, 3, 4, 5, 5, 15, 15, 5, 4, 4, 3, 3, 2, 2],
         "height":15,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }],
 "orientation":"isometric",
 "properties":
    {

    },
 "tileheight":40,
 "tilesets":[
        {
         "firstgid":1,
         "image":"grass-tile-wide-spritesheet.png",
         "imageheight":80,
         "imagewidth":400,
         "margin":0,
         "name":"GrassTile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"0,3",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"0,4",
                 "tileID":"4"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":6,
         "image":"stone-tile-wide-spritesheet.png",
         "imageheight":80,
         "imagewidth":400,
         "margin":0,
         "name":"Stone Tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"0,3",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"0,4",
                 "tileID":"4"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":11,
         "image":"water-tile-wide-spritesheet.png",
         "imageheight":80,
         "imagewidth":400,
         "margin":0,
         "name":"Water Tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"0,3",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"0,4",
                 "tileID":"4"
                }
            },
         "tilewidth":80
        }, 
        {
         "firstgid":16,
         "image":"sand-tile-wide-sprite-sheet.png",
         "imageheight":80,
         "imagewidth":400,
         "margin":0,
         "name":"Sand Tile",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":80,
         "tileproperties":
            {
             "0":
                {
                 "coords":"0,0",
                 "tileID":"0"
                },
             "1":
                {
                 "coords":"0,1",
                 "tileID":"1"
                },
             "2":
                {
                 "coords":"0,2",
                 "tileID":"2"
                },
             "3":
                {
                 "coords":"0,3",
                 "tileID":"3"
                },
             "4":
                {
                 "coords":"0,4",
                 "tileID":"4"
                }
            },
         "tilewidth":80
        }],
 "tilewidth":80,
 "version":1,
 "width":15
}
)